name: Bringsvor
favicon: null
layout_spectrum: 0.98431
typography_spectrum: 0.26898
title: The home of Audun Bringsvor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d4e3'
    - '#8b95ae'
    - '#513728'
    - '#835f49'
    - '#a27e68'
  brandStrength: 0.5260384229477495
  lightness: 0.3312296820804477
  saturation: 0.5760374886449426
  rhythmicContrast: 0.971617914037779
purpose: []
